### ISSUE TITLE
テナント削除バッチ、大量データの考慮、ストレージスペースデータが一部削除できない

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1289]
## 修正内容
- データ削除時に、一定数のデータ単位で少しずつ削除していくようにする。
- 途中で処理がストップしても再実行すれば途中から再開されるように。
- Oracle, PostgreSQL でストレージスペースを利用しているテーブルデータが削除できない。削除するよう不具合改修。
- SQL Server のパス区切り文字のOS依存を解消

**Comment by xsekiguchi** [comment]
( _English_ )

## Fixes
- When deleting data, delete a certain number of data units at a time.
- Even if the process is stopped in the middle of deleting data, it can be restarted by reexecuting the process.
- Table data using storage space cannot be deleted in Oracle and PostgreSQL. Fix bug so that it can be deleted.
