### ISSUE TITLE
GEM、検索結果のCSVダウンロードでReferencePropertyEditorの「表示ラベルとして扱うプロパティ」を考慮する

### ISSUE THREAD

**Issue by rikouki-isid** [ISID/iPLAss#1322]
GEM、検索結果のCSVダウンロードでReferencePropertyEditorの「表示ラベルとして扱うプロパティ」を考慮する。
ReferencePropertyEditorで「表示ラベルとして扱うプロパティ」として設定された項目をCSVダウンロード時にCSV項目として出力する。

後方互換性を保つため、GemConfigServiceにフラグを追加し、挙動を変更できるようにする（デフォルトでは、現状の挙動のまま）。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
GEM, consider "properties to be treated as display labels" in ReferencePropertyEditor when downloading CSV of search results.
Items set as "Properties to be treated as display labels" in ReferencePropertyEditor are output as CSV items when downloading CSV.

To maintain backward compatibility, add a flag to GemConfigService so that the behavior can be changed (by default, the current behavior is maintained).
