### ISSUE TITLE
DetailFormViewのアイテム表示判定スクリプトに対象Entityをバインドする

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#411]
DetailLayoutの各アイテムの表示判定スクリプトに対象Entityをバインドする。
バインドするEntityにはoidとversionのみセットし、新規作成の場合はnullでバインドする。
（SearchFormView、BulkFormViewはEntity単位ではないので除外）

詳細画面や編集画面に表示する対象データの状態で表示切替を可能にする。

合わせて、すでにバインドされているrequestについては、リクエストされるタイミングによって、パラメータは異なる可能性があることを注意書きで明示する。
（例えば、初期画面表示時と参照Entity選択後の名称取得処理のEditor取得時などではパラメータは異なる）

**Comment by houshiPLAss** [comment]
- GetAutocompletionValueCommand
- GetEntityNameListCommand
- GetEditorCommand
- GetReferenceLinkItemCommand
- GetReferenceUniqueItemCommand
- SearchTreeDataCommand

呼び出される箇所を対応必要あります。

**Comment by houshiPLAss** [comment]
すべてEntityViewUtil.isDisplayElementを呼び出すjavaクラスとjspファイル
を対応する必要があります。

**Comment by houshiPLAss** [comment]
_(English)_
Bind the target Entity to the DisplayScript for each item of DetailLayout.
Only oid and version are set for the entity to be bound, and when creating a new one, bind with null.
(SearchFormView and BulkFormView are excluded because they do not deal with per entity).

Make it possible to control item to be displayed on the Detail Page or the Edit Page according to the state of the target data.

In addition, for request that are already bound, note that the parameters may differ depending on the request timing.
(For example, the parameters are different at the time of page initialization and at the time of acquiring Editor definition for name acquisition processing after reference Entity selection).
