### ISSUE TITLE
ネストテーブルの表示順が正しく設定されない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#614]
行追加方法を「TOP」かつ、ネストテーブルの表示順プロパティを指定した場合、
編集時にはテーブルの先頭行に新規行が追加されるが、保存後の詳細画面では新規行が最後に表示されてしまう。

また、編集ページを「VIEW」にした場合に新規ボタンから登録した場合も、先頭ではなく最後に表示されてしまう。

**Comment by isid-maxingguo** [comment]
(English)
When the row addition method is `TOP` and the display order property of the nested table is specified
A new row is added to the first row of the table when editing, but the new row is displayed at the end on the detail screen after saving.

Also, when the edit page is set to `VIEW` and registered from the new button, it will be displayed at the end instead of the beginning.
