### ISSUE TITLE
AutoNumberPropertyEditor、ExpressionPropertyEditorの表示タイプに「TEXT」を追加

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#620]
AutoNumberPropertyEditor、ExpressionPropertyEditorの表示タイプに `TEXT` を追加する。

新しく `TEXT` を追加し、検索条件で入力モードとして動作するようにする。
（編集画面では、入力不可項目のためLABELと同様に動作）

現状、 `LABEL` と `HIDDEN` のみだが、検索条件設定では `LABEL` を指定してもテキスト入力として動作している。
`LABEL` については他のEditorと動作を合わせるため表示専用にしたいが、3.1系のバージョンでは現状の動作は変えない。

レイアウトの標準ロード時とアイテムDrop時のEditorの初期設定は、 `LABEL` ではなく `TEXT` に変更する。

**Comment by xkazama-yukio3** [comment]
See also https://github.com/ISID/iPLAss/issues/590

**Comment by isid-maxingguo** [comment]
(English)
Add `TEXT` to the display type of AutoNumberPropertyEditor and ExpressionPropertyEditor.

Add a new `TEXT` to make it work as an input mode in the search criteria.
(On the edit screen, it works in the same way as LABEL because it is a non-input item)

Currently, only `LABEL` and `HIDDEN` are available, but in the search condition settings, he works as a text input even if `LABEL` is specified.
Regarding `LABEL`, I want to dedicate it to display in order to match the operation with other editors, but the current operation does not change in the 3.1 series version.

The default setting of the Editor when loading a layout as standard and when dropping an item is changed to his `TEXT` instead of `LABEL`.
