### ISSUE TITLE
gem検索画面、検索結果のページング表示の改善

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#657]
gem検索画面、検索結果のページング表示を改善する。

- 検索結果が0件の場合、ページショートカットを表示しない（現状 `1` というショートカットが表示されている）
- ページ指定による検索時にそのページの結果が0件の場合、 `0件 / 全件数` として表示する

ページ指定による検索については、条件が変更された場合に0件になり得る。
その場合、

> 3/2 ページ    1 2 3   31-20/20件

のように表示されているので `31-20` 部分(ページで表示している範囲を表すところ)を `0` として表示する。

**Comment by isid-maxingguo** [comment]
(English)
Improve the gem search screen and the paging display of search results.

--If the search result is 0, the page shortcut is not displayed (currently, the shortcut `1` is displayed).
--If the result of the page is 0 when searching by specifying the page, it is displayed as `0 / total number`.

Search by page specification can be 0 if the conditions are changed.
In that case,

> 3/2 Page 1 2 3 31-20 / 20

Since it is displayed as, the `31-20` part (where the range displayed on the page is represented) is displayed as` 0`.
