### ISSUE TITLE
Entityに対応するRDB上でのViewを作成するツール

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#90]
Entityに対応するRDB上でのViewを作成するツールを提供する。
iPLAssのEntityデータ格納しているテーブルは特殊なので、RDBレベルで外部連携する際に扱いづらい。
外部連携する際に容易に扱うために、Entityに対応したViewを作成することを可能にする。

- 特定テナントを対象にするか、テナント横断でViewにするかを指定可能に。

**Comment by xwada** [comment]
(English)
Provides a tool to create View corresponding to Entity on RDB.
Since the table storing Entity data of iPLAss is special, it is difficult to handle when linking externally at RDB level.
It is possible to create a View corresponding to Entity to easily handle external linkage.

- It is possible to specify whether to target a specific tenant or to make it a view across tenants.

**Comment by xwada** [comment]
対応完了。
